using System.Collections.Generic;
using System.Text;
using DataNormalizer.Generators.Models;

namespace DataNormalizer.Generators.Emitters;

internal static class ContainerEmitter
{
    public static string Emit(
        TypeGraphNode rootNode,
        IReadOnlyList<TypeGraphNode> allNodes,
        NamingModel naming,
        JsonContractModel jsonContract
    )
    {
        var sb = new StringBuilder();
        var ns = EmitterHelpers.GetNamespace(rootNode.TypeFullName);
        var containerName = EmitterHelpers.GetContainerName(rootNode.TypeName, naming);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        sb.AppendLine(
            $"[System.CodeDom.Compiler.GeneratedCode(\"{EmitterHelpers.GeneratorName}\", \"{EmitterHelpers.GeneratorVersion}\")]"
        );
        sb.AppendLine($"public partial class {containerName}");
        sb.AppendLine("{");

        // Always emit the Result property for the root type
        var rootDtoFullName = EmitterHelpers.GetDtoFullName(
            rootNode.TypeFullName,
            rootNode.TypeName,
            naming
        );
        var rootJsonName = string.IsNullOrEmpty(jsonContract.RootPropertyName)
            ? "result"
            : jsonContract.RootPropertyName;
        sb.AppendLine(
            $"    [System.Text.Json.Serialization.JsonPropertyName(\"{rootJsonName}\")]"
        );
        sb.AppendLine($"    public {rootDtoFullName} Result {{ get; set; }} = default!;");

        // Emit list properties for each node
        for (var i = 0; i < allNodes.Count; i++)
        {
            var node = allNodes[i];

            // Skip list for root node if NeedsList is false
            if (node.IsRootType && !node.NeedsList)
                continue;

            var dtoFullName = EmitterHelpers.GetDtoFullName(
                node.TypeFullName,
                node.TypeName,
                naming
            );
            var listPropertyName = EmitterHelpers.GetListPropertyName(node, allNodes, naming);

            EmitJsonNamingAttribute(sb, node, listPropertyName, naming, jsonContract);
            sb.AppendLine(
                $"    public {dtoFullName}[] {listPropertyName} {{ get; set; }} = System.Array.Empty<{dtoFullName}>();"
            );
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitJsonNamingAttribute(
        StringBuilder sb,
        TypeGraphNode node,
        string propertyName,
        NamingModel naming,
        JsonContractModel jsonContract
    )
    {
        // Check for collection JSON name override first
        if (jsonContract.CollectionJsonNames.TryGetValue(node.TypeFullName, out var overrideName))
        {
            sb.AppendLine(
                $"    [System.Text.Json.Serialization.JsonPropertyName(\"{overrideName}\")]"
            );
            return;
        }

        if (!naming.EmitJsonPropertyNames)
            return;

        var camelName = EmitterHelpers.ToCamelCase(propertyName);
        sb.AppendLine(
            $"    [System.Text.Json.Serialization.JsonPropertyName(\"{camelName}\")]"
        );
    }
}
