using System.Collections.Generic;
using System.Text;
using DataNormalizer.Generators.Models;

namespace DataNormalizer.Generators.Emitters;

internal static class ContainerEmitter
{
    public static string Emit(TypeGraphNode rootNode, IReadOnlyList<TypeGraphNode> allNodes, string? jsonNamingPolicy)
    {
        var sb = new StringBuilder();
        var ns = EmitterHelpers.GetNamespace(rootNode.TypeFullName);
        var containerName = $"Normalized{rootNode.TypeName}Result";

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        sb.AppendLine(
            $"[System.CodeDom.Compiler.GeneratedCode(\"{EmitterHelpers.GeneratorName}\", \"{EmitterHelpers.GeneratorVersion}\")]"
        );
        sb.AppendLine($"public partial class {containerName}");
        sb.AppendLine("{");

        // Entity list properties for all types in the graph
        for (var i = 0; i < allNodes.Count; i++)
        {
            var node = allNodes[i];
            var dtoFullName = EmitterHelpers.GetDtoFullName(node.TypeFullName, node.TypeName);
            var listPropertyName = EmitterHelpers.GetListPropertyName(node, allNodes);

            EmitJsonNamingAttribute(sb, listPropertyName, jsonNamingPolicy);
            sb.AppendLine(
                $"    public {dtoFullName}[] {listPropertyName} {{ get; set; }} = System.Array.Empty<{dtoFullName}>();"
            );
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitJsonNamingAttribute(StringBuilder sb, string propertyName, string? jsonNamingPolicy)
    {
        if (jsonNamingPolicy is null)
            return;

        if (jsonNamingPolicy == EmitterHelpers.CamelCasePolicy)
        {
            var camelName = EmitterHelpers.ToCamelCase(propertyName);
            sb.AppendLine($"    [System.Text.Json.Serialization.JsonPropertyName(\"{camelName}\")]");
        }
    }
}
