using System.Collections.Generic;
using System.Text;
using DataNormalizer.Generators.Models;

namespace DataNormalizer.Generators.Emitters;

internal static class DenormalizerEmitter
{
    public static string Emit(NormalizationModel model, IReadOnlyList<TypeGraphNode> allNodes)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.ConfigNamespace))
        {
            sb.AppendLine($"namespace {model.ConfigNamespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"public partial class {model.ConfigClassName}");
        sb.AppendLine("{");

        var emittedRootCount = 0;
        foreach (var rootType in model.RootTypes)
        {
            var rootNode = EmitterHelpers.FindNode(allNodes, rootType.FullyQualifiedName);
            if (rootNode != null)
            {
                if (emittedRootCount > 0)
                {
                    sb.AppendLine();
                }

                EmitDenormalizeMethod(sb, rootType, rootNode, allNodes);
                emittedRootCount++;
            }
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitDenormalizeMethod(
        StringBuilder sb,
        RootTypeInfo rootType,
        TypeGraphNode rootNode,
        IReadOnlyList<TypeGraphNode> allNodes
    )
    {
        var containerFullName = GetContainerFullName(rootType.FullyQualifiedName, rootNode.TypeName);
        sb.AppendLine($"    public static {rootType.FullyQualifiedName} Denormalize({containerFullName} normalized)");
        sb.AppendLine("    {");

        // Collect all DTO collections
        EmitGetCollections(sb, allNodes);
        sb.AppendLine();

        // Pass 1: Create all source objects, populate simple + inlined properties
        EmitPass1(sb, allNodes);
        sb.AppendLine();

        // Pass 2: Resolve references (normalized + collection properties)
        EmitPass2(sb, allNodes);
        sb.AppendLine();

        // Find root by reference equality and return
        EmitRootResolution(sb, rootNode);

        sb.AppendLine("    }");
    }

    private static void EmitGetCollections(StringBuilder sb, IReadOnlyList<TypeGraphNode> allNodes)
    {
        for (var i = 0; i < allNodes.Count; i++)
        {
            var node = allNodes[i];
            var camel = ToCamelCase(node.TypeName);
            sb.AppendLine($"        var {camel}Dtos = normalized.{node.TypeName}List;");
        }
    }

    private static void EmitPass1(StringBuilder sb, IReadOnlyList<TypeGraphNode> allNodes)
    {
        for (var nodeIdx = 0; nodeIdx < allNodes.Count; nodeIdx++)
        {
            var node = allNodes[nodeIdx];
            var camel = ToCamelCase(node.TypeName);
            var plural = ToPlural(camel);

            if (nodeIdx > 0)
            {
                sb.AppendLine();
            }

            sb.AppendLine($"        var {plural} = new {node.TypeFullName}[{camel}Dtos.Length];");
            sb.AppendLine($"        for (var i = 0; i < {camel}Dtos.Length; i++)");
            sb.AppendLine("        {");
            sb.AppendLine($"            {plural}[i] = new {node.TypeFullName}();");

            foreach (var prop in node.Properties)
            {
                if (prop.Kind == PropertyKind.Simple)
                {
                    sb.AppendLine($"            {plural}[i].{prop.Name} = {camel}Dtos[i].{prop.Name};");
                }
                else if (prop.Kind == PropertyKind.Inlined)
                {
                    sb.AppendLine($"            {plural}[i].{prop.Name} = {camel}Dtos[i].{prop.Name};");
                }
            }

            sb.AppendLine("        }");
        }
    }

    private static void EmitPass2(StringBuilder sb, IReadOnlyList<TypeGraphNode> allNodes)
    {
        var emittedAny = false;
        for (var nodeIdx = 0; nodeIdx < allNodes.Count; nodeIdx++)
        {
            var node = allNodes[nodeIdx];
            if (!HasReferenceProperties(node))
            {
                continue;
            }

            var camel = ToCamelCase(node.TypeName);
            var plural = ToPlural(camel);

            if (emittedAny)
            {
                sb.AppendLine();
            }

            sb.AppendLine($"        for (var i = 0; i < {camel}Dtos.Length; i++)");
            sb.AppendLine("        {");

            foreach (var prop in node.Properties)
            {
                if (prop.Kind == PropertyKind.Normalized)
                {
                    EmitNormalizedResolution(sb, prop, plural, camel, allNodes);
                }
                else if (prop.Kind == PropertyKind.Collection)
                {
                    EmitCollectionResolution(sb, prop, plural, camel, allNodes);
                }
            }

            sb.AppendLine("        }");
            emittedAny = true;
        }
    }

    private static void EmitNormalizedResolution(
        StringBuilder sb,
        AnalyzedProperty prop,
        string plural,
        string camel,
        IReadOnlyList<TypeGraphNode> allNodes
    )
    {
        var targetNode = EmitterHelpers.FindNode(allNodes, prop.TypeFullName);
        var targetPlural = targetNode != null ? ToPlural(ToCamelCase(targetNode.TypeName)) : "unknown";

        if (prop.IsNullable)
        {
            sb.AppendLine(
                $"            {plural}[i].{prop.Name} = {camel}Dtos[i].{prop.Name}Index is {{ }} {ToCamelCase(prop.Name)}Idx ? {targetPlural}[{ToCamelCase(prop.Name)}Idx] : null;"
            );
        }
        else
        {
            sb.AppendLine($"            {plural}[i].{prop.Name} = {targetPlural}[{camel}Dtos[i].{prop.Name}Index];");
        }
    }

    private static void EmitCollectionResolution(
        StringBuilder sb,
        AnalyzedProperty prop,
        string plural,
        string camel,
        IReadOnlyList<TypeGraphNode> allNodes
    )
    {
        var elementTypeFullName = prop.CollectionElementTypeFullName ?? prop.TypeFullName;
        var elementNode = EmitterHelpers.FindNode(allNodes, elementTypeFullName);
        var elementPlural = elementNode != null ? ToPlural(ToCamelCase(elementNode.TypeName)) : "unknown";

        switch (prop.CollectionKind)
        {
            case CollectionTypeKind.List:
                EmitListReconstruction(sb, prop, plural, camel, elementTypeFullName, elementPlural);
                break;
            case CollectionTypeKind.Array:
                EmitArrayReconstruction(sb, prop, plural, camel, elementTypeFullName, elementPlural);
                break;
            case CollectionTypeKind.IReadOnlyList:
            case CollectionTypeKind.ICollection:
            case CollectionTypeKind.IList:
            case CollectionTypeKind.IEnumerable:
                EmitInterfaceCollectionReconstruction(sb, prop, plural, camel, elementTypeFullName, elementPlural);
                break;
            case CollectionTypeKind.HashSet:
                EmitHashSetReconstruction(sb, prop, plural, camel, elementTypeFullName, elementPlural);
                break;
            case CollectionTypeKind.ImmutableList:
                EmitImmutableListReconstruction(sb, prop, plural, camel, elementTypeFullName, elementPlural);
                break;
            case CollectionTypeKind.ImmutableArray:
                EmitImmutableArrayReconstruction(sb, prop, plural, camel, elementTypeFullName, elementPlural);
                break;
            default:
                // Default to List
                EmitListReconstruction(sb, prop, plural, camel, elementTypeFullName, elementPlural);
                break;
        }
    }

    private static void EmitListReconstruction(
        StringBuilder sb,
        AnalyzedProperty prop,
        string plural,
        string camel,
        string elementTypeFullName,
        string elementPlural
    )
    {
        sb.AppendLine(
            $"            {plural}[i].{prop.Name} = new System.Collections.Generic.List<{elementTypeFullName}>();"
        );
        sb.AppendLine($"            foreach (var idx in {camel}Dtos[i].{prop.Name}Indices)");
        sb.AppendLine($"                {plural}[i].{prop.Name}.Add({elementPlural}[idx]);");
    }

    private static void EmitArrayReconstruction(
        StringBuilder sb,
        AnalyzedProperty prop,
        string plural,
        string camel,
        string elementTypeFullName,
        string elementPlural
    )
    {
        sb.AppendLine(
            $"            {plural}[i].{prop.Name} = new {elementTypeFullName}[{camel}Dtos[i].{prop.Name}Indices.Length];"
        );
        sb.AppendLine($"            for (var j = 0; j < {camel}Dtos[i].{prop.Name}Indices.Length; j++)");
        sb.AppendLine(
            $"                {plural}[i].{prop.Name}[j] = {elementPlural}[{camel}Dtos[i].{prop.Name}Indices[j]];"
        );
    }

    private static void EmitInterfaceCollectionReconstruction(
        StringBuilder sb,
        AnalyzedProperty prop,
        string plural,
        string camel,
        string elementTypeFullName,
        string elementPlural
    )
    {
        var tempVar = $"temp{prop.Name}";
        sb.AppendLine($"            var {tempVar} = new System.Collections.Generic.List<{elementTypeFullName}>();");
        sb.AppendLine($"            foreach (var idx in {camel}Dtos[i].{prop.Name}Indices)");
        sb.AppendLine($"                {tempVar}.Add({elementPlural}[idx]);");
        sb.AppendLine($"            {plural}[i].{prop.Name} = {tempVar};");
    }

    private static void EmitHashSetReconstruction(
        StringBuilder sb,
        AnalyzedProperty prop,
        string plural,
        string camel,
        string elementTypeFullName,
        string elementPlural
    )
    {
        sb.AppendLine(
            $"            {plural}[i].{prop.Name} = new System.Collections.Generic.HashSet<{elementTypeFullName}>();"
        );
        sb.AppendLine($"            foreach (var idx in {camel}Dtos[i].{prop.Name}Indices)");
        sb.AppendLine($"                {plural}[i].{prop.Name}.Add({elementPlural}[idx]);");
    }

    private static void EmitImmutableListReconstruction(
        StringBuilder sb,
        AnalyzedProperty prop,
        string plural,
        string camel,
        string elementTypeFullName,
        string elementPlural
    )
    {
        var tempVar = $"temp{prop.Name}";
        sb.AppendLine(
            $"            var {tempVar} = System.Collections.Immutable.ImmutableList.CreateBuilder<{elementTypeFullName}>();"
        );
        sb.AppendLine($"            foreach (var idx in {camel}Dtos[i].{prop.Name}Indices)");
        sb.AppendLine($"                {tempVar}.Add({elementPlural}[idx]);");
        sb.AppendLine($"            {plural}[i].{prop.Name} = {tempVar}.ToImmutable();");
    }

    private static void EmitImmutableArrayReconstruction(
        StringBuilder sb,
        AnalyzedProperty prop,
        string plural,
        string camel,
        string elementTypeFullName,
        string elementPlural
    )
    {
        var tempVar = $"temp{prop.Name}";
        sb.AppendLine(
            $"            var {tempVar} = System.Collections.Immutable.ImmutableArray.CreateBuilder<{elementTypeFullName}>();"
        );
        sb.AppendLine($"            foreach (var idx in {camel}Dtos[i].{prop.Name}Indices)");
        sb.AppendLine($"                {tempVar}.Add({elementPlural}[idx]);");
        sb.AppendLine($"            {plural}[i].{prop.Name} = {tempVar}.ToImmutable();");
    }

    private static void EmitRootResolution(StringBuilder sb, TypeGraphNode rootNode)
    {
        var plural = ToPlural(ToCamelCase(rootNode.TypeName));

        sb.AppendLine($"        return {plural}[normalized.RootIndex];");
    }

    private static bool HasReferenceProperties(TypeGraphNode node)
    {
        foreach (var prop in node.Properties)
        {
            if (prop.Kind == PropertyKind.Normalized || prop.Kind == PropertyKind.Collection)
            {
                return true;
            }
        }

        return false;
    }

}
