using System.Text;
using DataNormalizer.Generators.Models;

namespace DataNormalizer.Generators.Emitters;

internal static class DtoEmitter
{
    public static string Emit(TypeGraphNode node) => Emit(node, copySourceAttributes: false, jsonNamingPolicy: null);

    public static string Emit(TypeGraphNode node, bool copySourceAttributes, string? jsonNamingPolicy)
    {
        var sb = new StringBuilder();
        var ns = EmitterHelpers.GetNamespace(node.TypeFullName);
        var dtoName = $"Normalized{node.TypeName}";

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(ns))
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        sb.AppendLine($"[System.CodeDom.Compiler.GeneratedCode(\"DataNormalizer\", \"1.0.0\")]");
        sb.AppendLine($"public partial class {dtoName} : System.IEquatable<{dtoName}>");
        sb.AppendLine("{");

        foreach (var prop in node.Properties)
        {
            EmitProperty(sb, prop, copySourceAttributes, jsonNamingPolicy);
        }

        sb.AppendLine();
        EmitTypedEquals(sb, dtoName, node.Properties);
        EmitObjectEquals(sb, dtoName);

        // Cache fields for GetHashCode
        sb.AppendLine("    private int _cachedHashCode;");
        sb.AppendLine("    private bool _hashComputed;");
        sb.AppendLine();
        EmitGetHashCode(sb, node.Properties);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitProperty(
        StringBuilder sb,
        AnalyzedProperty prop,
        bool copySourceAttributes,
        string? jsonNamingPolicy
    )
    {
        switch (prop.Kind)
        {
            case PropertyKind.Simple:
                EmitSourceAttributes(sb, prop, copySourceAttributes);
                EmitJsonNamingAttribute(sb, prop, prop.Name, jsonNamingPolicy);
                EmitSimpleProperty(sb, prop);
                break;
            case PropertyKind.Normalized:
                EmitJsonNamingAttribute(sb, prop, $"{prop.Name}Index", jsonNamingPolicy);
                EmitNormalizedProperty(sb, prop);
                break;
            case PropertyKind.Collection:
                EmitJsonNamingAttribute(sb, prop, $"{prop.Name}Indices", jsonNamingPolicy);
                EmitCollectionProperty(sb, prop);
                break;
            case PropertyKind.Inlined:
                EmitSourceAttributes(sb, prop, copySourceAttributes);
                EmitJsonNamingAttribute(sb, prop, prop.Name, jsonNamingPolicy);
                EmitInlinedProperty(sb, prop);
                break;
        }
    }

    private static void EmitJsonNamingAttribute(
        StringBuilder sb,
        AnalyzedProperty prop,
        string propertyName,
        string? jsonNamingPolicy
    )
    {
        if (jsonNamingPolicy is null)
            return;

        if (HasJsonPropertyNameAttribute(prop))
            return;

        if (jsonNamingPolicy == "CamelCase")
        {
            var camelName = EmitterHelpers.ToCamelCase(propertyName);
            sb.AppendLine($"    [System.Text.Json.Serialization.JsonPropertyName(\"{camelName}\")]");
        }
    }

    private static bool HasJsonPropertyNameAttribute(AnalyzedProperty prop)
    {
        foreach (var attr in prop.SourceAttributes)
        {
            if (attr.Contains("JsonPropertyName"))
                return true;
        }

        return false;
    }

    private static void EmitSourceAttributes(StringBuilder sb, AnalyzedProperty prop, bool copySourceAttributes)
    {
        if (!copySourceAttributes)
            return;

        foreach (var attr in prop.SourceAttributes)
        {
            sb.AppendLine($"    {attr}");
        }
    }

    private static void EmitSimpleProperty(StringBuilder sb, AnalyzedProperty prop)
    {
        var defaultValue = prop.IsReferenceType ? " = default!;" : "";
        sb.AppendLine($"    public {prop.TypeFullName} {prop.Name} {{ get; set; }}{defaultValue}");
    }

    private static void EmitNormalizedProperty(StringBuilder sb, AnalyzedProperty prop)
    {
        var type = prop.IsNullable ? "int?" : "int";
        sb.AppendLine($"    public {type} {prop.Name}Index {{ get; set; }}");
    }

    private static void EmitCollectionProperty(StringBuilder sb, AnalyzedProperty prop)
    {
        sb.AppendLine($"    public int[] {prop.Name}Indices {{ get; set; }} = System.Array.Empty<int>();");
    }

    private static void EmitInlinedProperty(StringBuilder sb, AnalyzedProperty prop)
    {
        var defaultValue = prop.IsReferenceType ? " = default!;" : "";
        sb.AppendLine($"    public {prop.TypeFullName} {prop.Name} {{ get; set; }}{defaultValue}");
    }

    private static void EmitTypedEquals(
        StringBuilder sb,
        string dtoName,
        System.Collections.Immutable.ImmutableArray<AnalyzedProperty> properties
    )
    {
        sb.AppendLine($"    public bool Equals({dtoName}? other)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (other is null) return false;");
        sb.AppendLine("        if (ReferenceEquals(this, other)) return true;");

        var equalityProps = new System.Collections.Generic.List<AnalyzedProperty>();
        foreach (var prop in properties)
        {
            if (!prop.IsCircularReference)
            {
                equalityProps.Add(prop);
            }
        }

        if (equalityProps.Count > 0)
        {
            sb.Append("        return ");

            for (var i = 0; i < equalityProps.Count; i++)
            {
                if (i > 0)
                {
                    sb.Append("            && ");
                }

                var prop = equalityProps[i];
                switch (prop.Kind)
                {
                    case PropertyKind.Simple:
                        sb.Append($"{prop.Name} == other.{prop.Name}");
                        break;
                    case PropertyKind.Normalized:
                        sb.Append($"{prop.Name}Index == other.{prop.Name}Index");
                        break;
                    case PropertyKind.Collection:
                        sb.Append(
                            $"System.MemoryExtensions.SequenceEqual(System.MemoryExtensions.AsSpan({prop.Name}Indices), System.MemoryExtensions.AsSpan(other.{prop.Name}Indices))"
                        );
                        break;
                    case PropertyKind.Inlined:
                        sb.Append(
                            $"System.Collections.Generic.EqualityComparer<{prop.TypeFullName}>.Default.Equals({prop.Name}, other.{prop.Name})"
                        );
                        break;
                }

                if (i < equalityProps.Count - 1)
                {
                    sb.AppendLine();
                }
            }

            sb.AppendLine(";");
        }
        else
        {
            sb.AppendLine("        return true;");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitObjectEquals(StringBuilder sb, string dtoName)
    {
        sb.AppendLine($"    public override bool Equals(object? obj) => obj is {dtoName} other && Equals(other);");
        sb.AppendLine();
    }

    private static void EmitGetHashCode(
        StringBuilder sb,
        System.Collections.Immutable.ImmutableArray<AnalyzedProperty> properties
    )
    {
        sb.AppendLine("    public override int GetHashCode()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (_hashComputed) return _cachedHashCode;");
        sb.AppendLine("        var hash = 17;");

        foreach (var prop in properties)
        {
            if (prop.IsCircularReference)
                continue;

            switch (prop.Kind)
            {
                case PropertyKind.Simple:
                    if (prop.IsReferenceType)
                    {
                        sb.AppendLine($"        hash = (hash * 397) ^ ({prop.Name}?.GetHashCode() ?? 0);");
                    }
                    else
                    {
                        sb.AppendLine($"        hash = (hash * 397) ^ {prop.Name}.GetHashCode();");
                    }
                    break;
                case PropertyKind.Normalized:
                    sb.AppendLine($"        hash = (hash * 397) ^ {prop.Name}Index.GetHashCode();");
                    break;
                case PropertyKind.Collection:
                    sb.AppendLine($"        hash = (hash * 397) ^ ({prop.Name}Indices?.Length ?? 0);");
                    sb.AppendLine($"        if ({prop.Name}Indices is {{ Length: > 0 }})");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            hash = (hash * 397) ^ {prop.Name}Indices[0].GetHashCode();");
                    sb.AppendLine($"            if ({prop.Name}Indices.Length > 1)");
                    sb.AppendLine(
                        $"                hash = (hash * 397) ^ {prop.Name}Indices[{prop.Name}Indices.Length - 1].GetHashCode();"
                    );
                    sb.AppendLine("        }");
                    break;
                case PropertyKind.Inlined:
                    if (prop.IsReferenceType)
                    {
                        sb.AppendLine($"        hash = (hash * 397) ^ ({prop.Name}?.GetHashCode() ?? 0);");
                    }
                    else
                    {
                        sb.AppendLine($"        hash = (hash * 397) ^ {prop.Name}.GetHashCode();");
                    }
                    break;
            }
        }

        sb.AppendLine("        _cachedHashCode = hash;");
        sb.AppendLine("        _hashComputed = true;");
        sb.AppendLine("        return hash;");
        sb.AppendLine("    }");
    }
}
