using System.Collections.Generic;
using System.Text;
using DataNormalizer.Generators.Models;

namespace DataNormalizer.Generators.Emitters;

internal static class NormalizerEmitter
{
    public static string Emit(NormalizationModel model, IReadOnlyList<TypeGraphNode> allNodes) =>
        Emit(model, allNodes, new Dictionary<string, IReadOnlyList<TypeGraphNode>>());

    public static string Emit(
        NormalizationModel model,
        IReadOnlyList<TypeGraphNode> allNodes,
        Dictionary<string, IReadOnlyList<TypeGraphNode>> perRootNodes
    )
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.ConfigNamespace))
        {
            sb.AppendLine($"namespace {model.ConfigNamespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"public partial class {model.ConfigClassName}");
        sb.AppendLine("{");

        var emittedRootCount = 0;
        foreach (var rootType in model.RootTypes)
        {
            var rootNode = EmitterHelpers.FindNode(allNodes, rootType.FullyQualifiedName);
            if (rootNode != null)
            {
                if (emittedRootCount > 0)
                {
                    sb.AppendLine();
                }

                var rootSpecificNodes = perRootNodes.ContainsKey(rootType.FullyQualifiedName)
                    ? perRootNodes[rootType.FullyQualifiedName]
                    : allNodes;
                EmitPublicNormalizeMethod(sb, rootType, rootNode, model, rootSpecificNodes);
                emittedRootCount++;
            }
        }

        for (var i = 0; i < allNodes.Count; i++)
        {
            var node = allNodes[i];
            if (i > 0 || emittedRootCount > 0)
            {
                sb.AppendLine();
            }

            EmitNormalizeHelper(sb, node, model);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitPublicNormalizeMethod(
        StringBuilder sb,
        RootTypeInfo rootType,
        TypeGraphNode rootNode,
        NormalizationModel model,
        IReadOnlyList<TypeGraphNode> allNodes
    )
    {
        var containerFullName = EmitterHelpers.GetContainerFullName(rootType.FullyQualifiedName, rootNode.TypeName);

        sb.AppendLine($"    public static {containerFullName} Normalize({rootType.FullyQualifiedName} source)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var context = new DataNormalizer.Runtime.NormalizationContext({allNodes.Count});");
        sb.AppendLine($"        var rootIndex = Normalize{rootNode.TypeName}(source, context);");
        sb.AppendLine($"        var result = new {containerFullName}();");
        sb.AppendLine("        result.RootIndex = rootIndex;");

        // Populate entity lists for each type in the graph
        for (var i = 0; i < allNodes.Count; i++)
        {
            var node = allNodes[i];
            var dtoFullName = EmitterHelpers.GetDtoFullName(node.TypeFullName, node.TypeName);
            var typeKey = EmitterHelpers.GetTypeKey(node, model);
            var camel = EmitterHelpers.ToCamelCase(node.TypeName);

            sb.AppendLine($"        var __{camel}Col = context.GetCollection<{dtoFullName}>(\"{typeKey}\");");
            sb.AppendLine($"        var __{camel}Arr = new {dtoFullName}[__{camel}Col.Count];");
            sb.AppendLine($"        for (var __i = 0; __i < __{camel}Col.Count; __i++)");
            sb.AppendLine($"            __{camel}Arr[__i] = __{camel}Col[__i];");
            sb.AppendLine($"        result.{node.TypeName}List = __{camel}Arr;");
        }

        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
    }

    private static void EmitNormalizeHelper(StringBuilder sb, TypeGraphNode node, NormalizationModel model)
    {
        var typeName = node.TypeName;
        var typeKey = EmitterHelpers.GetTypeKey(node, model);
        var dtoFullName = EmitterHelpers.GetDtoFullName(node.TypeFullName, typeName);

        sb.AppendLine(
            $"    private static int Normalize{typeName}({node.TypeFullName} source, DataNormalizer.Runtime.NormalizationContext context)"
        );
        sb.AppendLine("    {");

        if (node.HasCircularReference)
        {
            // Reference-based cycle detection guard (opt-in)
            if (model.UseReferenceTrackingForCycles)
            {
                sb.AppendLine("        if (context.TryGetTrackedIndex(source, out var existingIdx))");
                sb.AppendLine("            return existingIdx;");
                sb.AppendLine();
            }

            // Two-DTO pattern: keyDto for value equality dedup + cycle detection
            // Group A: Simple, Inlined, and non-circular Normalized/Collection (safe to normalize first)
            // Group B: Circular Normalized/Collection (normalize after GetOrAddIndex to break cycles)
            sb.AppendLine($"        var keyDto = new {dtoFullName}();");

            // === Group A: Simple + Inlined properties on keyDto ===
            foreach (var prop in node.Properties)
            {
                if (prop.Kind == PropertyKind.Simple || prop.Kind == PropertyKind.Inlined)
                {
                    sb.AppendLine($"        keyDto.{prop.Name} = source.{prop.Name};");
                }
            }

            // === Group A: Non-circular Normalized properties on keyDto (real indices) ===
            foreach (var prop in node.Properties)
            {
                if (prop.Kind == PropertyKind.Normalized && !prop.IsCircularReference)
                {
                    EmitKeyDtoNonCircularNormalizedProperty(sb, prop);
                }
            }

            // === Group A: Non-circular Collection properties on keyDto (real indices) ===
            foreach (var prop in node.Properties)
            {
                if (prop.Kind == PropertyKind.Collection && !prop.IsCircularReference)
                {
                    EmitKeyDtoNonCircularCollectionProperty(sb, prop);
                }
            }

            // Circular properties: left at defaults (excluded from equality, no need to encode)

            // Check for existing entry (value equality dedup + cycle detection)
            sb.AppendLine();
            sb.AppendLine($"        var (index, isNew) = context.GetOrAddIndexAndStore(\"{typeKey}\", keyDto);");
            sb.AppendLine("        if (!isNew)");
            sb.AppendLine("            return index;");

            // Reference-based tracking: record source → index after AddToCollection, before circular recursion
            if (model.UseReferenceTrackingForCycles)
            {
                sb.AppendLine("        context.TrackSource(source, index);");
            }

            sb.AppendLine();

            // === Group B: Now normalize circular properties (recursion happens here) ===
            foreach (var prop in node.Properties)
            {
                if (prop.Kind == PropertyKind.Normalized && prop.IsCircularReference)
                {
                    EmitComplexPropertyAssignment(sb, prop);
                }
                else if (prop.Kind == PropertyKind.Collection && prop.IsCircularReference)
                {
                    EmitComplexCollectionAssignment(sb, prop);
                }
            }

            // Create full DTO with all properties and overwrite collection entry
            sb.AppendLine();
            sb.AppendLine($"        var fullDto = new {dtoFullName}();");

            // Copy ALL properties onto fullDto
            foreach (var prop in node.Properties)
            {
                if (prop.Kind == PropertyKind.Simple || prop.Kind == PropertyKind.Inlined)
                {
                    sb.AppendLine($"        fullDto.{prop.Name} = source.{prop.Name};");
                }
                else if (prop.Kind == PropertyKind.Normalized)
                {
                    var indexPropName = $"{prop.Name}Index";
                    if (prop.IsCircularReference)
                    {
                        // Group B: use the real value from the local variable
                        sb.AppendLine(
                            $"        fullDto.{indexPropName} = {EmitterHelpers.ToCamelCase(prop.Name)}Index;"
                        );
                    }
                    else
                    {
                        // Group A: reuse the value already computed on keyDto
                        sb.AppendLine($"        fullDto.{indexPropName} = keyDto.{indexPropName};");
                    }
                }
                else if (prop.Kind == PropertyKind.Collection)
                {
                    var indicesPropName = $"{prop.Name}Indices";
                    if (prop.IsCircularReference)
                    {
                        // Group B: use the real value from the local variable
                        sb.AppendLine(
                            $"        fullDto.{indicesPropName} = {EmitterHelpers.ToCamelCase(prop.Name)}Indices;"
                        );
                    }
                    else
                    {
                        // Group A: reuse the value already computed on keyDto
                        sb.AppendLine($"        fullDto.{indicesPropName} = keyDto.{indicesPropName};");
                    }
                }
            }

            sb.AppendLine($"        context.AddToCollection(\"{typeKey}\", index, fullDto);");
            sb.AppendLine();
            sb.AppendLine("        return index;");
        }
        else
        {
            // Non-circular pattern: all props, then register
            sb.AppendLine($"        var dto = new {dtoFullName}();");

            foreach (var prop in node.Properties)
            {
                EmitPropertyAssignment(sb, prop, typeName, node);
            }

            sb.AppendLine();
            sb.AppendLine($"        var (index, isNew) = context.GetOrAddIndexAndStore(\"{typeKey}\", dto);");
            sb.AppendLine("        return index;");
        }

        sb.AppendLine("    }");
    }

    private static void EmitPropertyAssignment(
        StringBuilder sb,
        AnalyzedProperty prop,
        string parentTypeName,
        TypeGraphNode parentNode
    )
    {
        switch (prop.Kind)
        {
            case PropertyKind.Simple:
                sb.AppendLine($"        dto.{prop.Name} = source.{prop.Name};");
                break;

            case PropertyKind.Normalized:
                EmitNormalizedPropertyAssignment(sb, prop);
                break;

            case PropertyKind.Collection:
                EmitCollectionPropertyAssignment(sb, prop);
                break;

            case PropertyKind.Inlined:
                sb.AppendLine($"        dto.{prop.Name} = source.{prop.Name};");
                break;
        }
    }

    private static void EmitNormalizedPropertyAssignment(StringBuilder sb, AnalyzedProperty prop)
    {
        var nestedTypeName = EmitterHelpers.GetShortTypeName(prop.TypeFullName);
        var indexPropName = $"{prop.Name}Index";

        if (prop.IsNullable)
        {
            sb.AppendLine(
                $"        dto.{indexPropName} = source.{prop.Name} is null ? (int?)null : Normalize{nestedTypeName}(source.{prop.Name}, context);"
            );
        }
        else
        {
            sb.AppendLine($"        dto.{indexPropName} = Normalize{nestedTypeName}(source.{prop.Name}, context);");
        }
    }

    private static void EmitCollectionPropertyAssignment(StringBuilder sb, AnalyzedProperty prop)
    {
        var elementTypeName =
            prop.CollectionElementTypeFullName != null
                ? EmitterHelpers.GetShortTypeName(prop.CollectionElementTypeFullName)
                : EmitterHelpers.GetShortTypeName(prop.TypeFullName);
        var indicesPropName = $"{prop.Name}Indices";

        EmitCollectionForLoop(
            sb,
            prop,
            elementTypeName,
            $"source.{prop.Name}",
            $"dto.{indicesPropName}",
            indent: "        "
        );
    }

    private static void EmitComplexPropertyAssignment(StringBuilder sb, AnalyzedProperty prop)
    {
        var nestedTypeName = EmitterHelpers.GetShortTypeName(prop.TypeFullName);
        var varName = $"{EmitterHelpers.ToCamelCase(prop.Name)}Index";

        if (prop.IsNullable)
        {
            sb.AppendLine(
                $"        var {varName} = source.{prop.Name} is null ? (int?)null : Normalize{nestedTypeName}(source.{prop.Name}, context);"
            );
        }
        else
        {
            sb.AppendLine($"        var {varName} = Normalize{nestedTypeName}(source.{prop.Name}, context);");
        }
    }

    private static void EmitComplexCollectionAssignment(StringBuilder sb, AnalyzedProperty prop)
    {
        var elementTypeName =
            prop.CollectionElementTypeFullName != null
                ? EmitterHelpers.GetShortTypeName(prop.CollectionElementTypeFullName)
                : EmitterHelpers.GetShortTypeName(prop.TypeFullName);
        var varName = $"{EmitterHelpers.ToCamelCase(prop.Name)}Indices";

        EmitCollectionForLoop(
            sb,
            prop,
            elementTypeName,
            $"source.{prop.Name}",
            varName,
            indent: "        ",
            useVar: true
        );
    }

    private static void EmitKeyDtoNonCircularNormalizedProperty(StringBuilder sb, AnalyzedProperty prop)
    {
        var nestedTypeName = EmitterHelpers.GetShortTypeName(prop.TypeFullName);
        var indexPropName = $"{prop.Name}Index";

        if (prop.IsNullable)
        {
            sb.AppendLine(
                $"        keyDto.{indexPropName} = source.{prop.Name} is null ? (int?)null : Normalize{nestedTypeName}(source.{prop.Name}, context);"
            );
        }
        else
        {
            sb.AppendLine($"        keyDto.{indexPropName} = Normalize{nestedTypeName}(source.{prop.Name}, context);");
        }
    }

    private static void EmitKeyDtoNonCircularCollectionProperty(StringBuilder sb, AnalyzedProperty prop)
    {
        var elementTypeName =
            prop.CollectionElementTypeFullName != null
                ? EmitterHelpers.GetShortTypeName(prop.CollectionElementTypeFullName)
                : EmitterHelpers.GetShortTypeName(prop.TypeFullName);
        var indicesPropName = $"{prop.Name}Indices";

        EmitCollectionForLoop(
            sb,
            prop,
            elementTypeName,
            $"source.{prop.Name}",
            $"keyDto.{indicesPropName}",
            indent: "        "
        );
    }

    private static bool IsIndexableCollection(CollectionTypeKind kind) =>
        kind
            is CollectionTypeKind.Array
                or CollectionTypeKind.List
                or CollectionTypeKind.IReadOnlyList
                or CollectionTypeKind.IList
                or CollectionTypeKind.ICollection
                or CollectionTypeKind.ImmutableList
                or CollectionTypeKind.ImmutableArray;

    private static string GetCountAccessor(CollectionTypeKind kind) =>
        kind == CollectionTypeKind.Array ? "Length" : "Count";

    private static void EmitCollectionForLoop(
        StringBuilder sb,
        AnalyzedProperty prop,
        string elementTypeName,
        string sourceExpr,
        string targetExpr,
        string indent,
        bool useVar = false
    )
    {
        var kind = prop.CollectionKind;

        // When declaring a local variable, declare it before the if/else so it's in scope afterwards
        if (useVar)
        {
            sb.AppendLine($"{indent}int[] {targetExpr};");
        }

        sb.AppendLine($"{indent}if ({sourceExpr} is null)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    {targetExpr} = System.Array.Empty<int>();");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine($"{indent}else");
        sb.AppendLine($"{indent}{{");

        if (IsIndexableCollection(kind))
        {
            var countAccessor = GetCountAccessor(kind);
            sb.AppendLine($"{indent}    var __col = {sourceExpr};");
            sb.AppendLine($"{indent}    var __indices = new int[__col.{countAccessor}];");
            sb.AppendLine($"{indent}    for (var __i = 0; __i < __col.{countAccessor}; __i++)");
            sb.AppendLine($"{indent}        __indices[__i] = Normalize{elementTypeName}(__col[__i], context);");
            sb.AppendLine($"{indent}    {targetExpr} = __indices;");
        }
        else
        {
            // HashSet, IEnumerable — no indexer, use foreach with List builder
            sb.AppendLine($"{indent}    var __list = new System.Collections.Generic.List<int>();");
            sb.AppendLine($"{indent}    foreach (var __item in {sourceExpr})");
            sb.AppendLine($"{indent}        __list.Add(Normalize{elementTypeName}(__item, context));");
            sb.AppendLine($"{indent}    {targetExpr} = __list.ToArray();");
        }

        sb.AppendLine($"{indent}}}");
    }
}
